### ISSUE TITLE
Cannot bind argument to parameter 'NetworkInterface' because it is null

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/SAP-on-Azure-Scripts-and-Utilities#106]
I am trying to use this script, but keep running into the same issue when it tries to create the SSH sessions:

Waiting for four minute for all systems to come up ...
WARNING: No known host file found, /home/morten/.poshssh/hosts.json
Creating SSH sessions
Get-AzNetworkInterfaceIpConfig: /home/morten/AvZone-Latency-Test.ps1:268
Line |
 268 |  … terfaceconfig = Get-AzNetworkInterfaceIpConfig -NetworkInterface $nic
     |                                                                     ~~~~
     | Cannot bind argument to parameter 'NetworkInterface' because it is null.

**Comment by msftphleiten** [comment]
can you please provide the full log and the command that you ran, thank you
