### ISSUE TITLE
Cannot validate argument on parameter 'SAPVMs'

### ISSUE THREAD

**Issue by mkjarvis1** [Azure/SAP-on-Azure-Scripts-and-Utilities#110]
Hello,

I am facing the issue while running the runbook "Start-SAPSystem" or "Stop-SAPSystem" 

Error - 
Show-AzSAPSIDVMApplicationInstances : Cannot validate argument on parameter 'SAPVMs'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. At line:112 char:45 + Show-AzSAPSIDVMApplicationInstances -SAPVMs $SAPSIDApplicationVMs + ~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidData: (:) [Show-AzSAPSIDVMApplicationInstances], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationError,Show-AzSAPSIDVMApplicationInstances

The same code is working fine for other set of servers.
I have made sure that the "Virtual Machine Contributor" access has been given to the VM which is causing a problem.
What can be the issue here ?
<img width="946" alt="SAPautomationissue" src="https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/assets/137192142/bdd53527-0100-4cc8-b0ee-dcfb725ef410">

**Comment by goraco** [comment]
hello @mkjarvis1 
can you please check that ALL tags on VMs are available and properly set?

thanks

**Comment by mkjarvis1** [comment]
Oh Thanks a tonne!!!
Got fixed after fetching the right Tags to the VM. :)

**Comment by goraco** [comment]
super, great to hear that it helped! ;-)
