### ISSUE TITLE
QCR Report Running

### ISSUE THREAD

**Issue by mishraankit08** [Azure/SAP-on-Azure-Scripts-and-Utilities#115]
We have issues running Quality Check report for any Linux VM

The behavior is inconsistent. 

Get-AzSubscription: C:\\Users\\vnadmin\\qcr\\SAP-on-Azure-Scripts-and-Utilities-main\\QualityCheck\\QualityCheck.ps1:1164
Line |
1164 |      $_SubscriptionInfo = Get-AzSubscription
     |                           ~~~~~~~~~~~~~~~~~~
     | An error occurred while sending the request.
ERROR    - Please connect to Azure using the Connect-AzAccount command, if you are connected use the Select-AzSubscription command to set the correct context

Another error message:
Get-AzSubscription: C:\\Users\\vnadmin\\qcr\\SAP-on-Azure-Scripts-and-Utilities-main\\QualityCheck\\QualityCheck.ps1:1164
Line |
1164 |      $_SubscriptionInfo = Get-AzSubscription
     |                           ~~~~~~~~~~~~~~~~~~
     | An error occurred while sending the request.
ERROR    - Please connect to Azure using the Connect-AzAccount command, if you are connected use the Select-AzSubscription command to set the correct context

**Comment by msftphleiten** [comment]
can you please provide more details including:
- which powershell version you are running
- which powershell module of Azure is installed
- what is the command that you are running when starting quality check
- what is the output if you run "Get-AzSubscritpion" manually

**Comment by mishraankit08** [comment]
Sure. Please find below the details:

•	which powershell version you are running ->PowerShell 7.4.1
•	which powershell module of Azure is installed ->
Install-Module Az -Force
Install-Module Az.NetAppFiles -Force
Install-Module Posh-SSH -Force
•	what is the command that you are running when starting quality check ->.\QualityCheck.ps1  -MultiRun -ImportFile QCRInput_HDB.txt
•	what is the output if you run "Get-AzSubscritpion" manually
PS C:\Users\vnadmin\qcr\SAP-on-Azure-Scripts-and-Utilities-main\QualityCheck> Get-AzSubscription -SubscriptionId 4a1f6aa1-ccab-4d40-ab30-cab8186900e0
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
Get-AzSubscription: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
PS C:\Users\vnadmin\qcr\SAP-on-Azure-Scripts-and-Utilities-main\QualityCheck>

**Comment by msftphleiten** [comment]
is it working with a run for a single VM, not using multirun?
this seems not to be related to quality check itself as the call httpclient timeout is what causes the issue.

**Comment by mishraankit08** [comment]
Tried for both. The response is inconsistent.
PS C:\Users\vnadmin\qcr\SAP-on-Azure-Scripts-and-Utilities-main\QualityCheck> .\QualityCheck.ps1  -GUI
INFO     - Start 04/15/2024 09:13:01
INFO     - Quality Check for SAP on Azure systems is provided under MIT license
INFO     - see https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/blob/main/LICENSE for details
Get-AzSubscription: C:\Users\vnadmin\qcr\SAP-on-Azure-Scripts-and-Utilities-main\QualityCheck\QualityCheck.ps1:3120
Line |
3120 |      $_SubscriptionInfo = Get-AzSubscription
     |                           ~~~~~~~~~~~~~~~~~~
     | An error occurred while sending the request.
ERROR    - Please connect to Azure using the Connect-AzAccount command, if you are connected use the Select-AzSubscription command to set the correct context

**Comment by msftphleiten** [comment]
pushed a quick fix, no new version, please download the new ps1 file

**Comment by mishraankit08** [comment]
Have run using the new file. It runs but still errors out 
INFO     - Start 04/15/2024 12:14:25
INFO     - Quality Check for SAP on Azure systems is provided under MIT license
INFO     - see https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/blob/main/LICENSE for details
INFO     - Reading file for Quality Check runs
INFO     - Read 4 entries in file
Enter Password: : **********
INFO     - Module Posh-SSH installed
INFO     - Module Az.Compute installed
INFO     - Module Az.Network installed
INFO     - Module Az.NetAppFiles installed
INFO     - Script Version 2024040502
Get-AzSubscription: C:\Users\vnadmin\qcr\SAP-on-Azure-Scripts-and-Utilities-main\QualityCheck\QualityCheck.ps1:1165
Line |
1165 |  … ptionInfo = Get-AzSubscription -SubscriptionId (Get-AzContext).Subscr …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | An error occurred while sending the request.
ERROR    - Please connect to Azure using the Connect-AzAccount command, if you are connected use the Select-AzSubscription command to set the correct context

**Comment by msftphleiten** [comment]
What is the output for
Get-AzSubscription -SubscriptionId (Get-AzContext).Subscription

Can you please also share the powershell module versions for Az.Accounts and Az.Subscription

**Comment by mishraankit08** [comment]
PS C:\Users\ankit> Get-AzSubscription -SubscriptionId (Get-AzContext).Subscription
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
WARNING: Unable to acquire token for tenant '' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user ankit.mishra@vnomic.com. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'

   TenantId: 918079db-c902-4e29-b22c-9764410d0375

Name                Id                                   State
----                --                                   -----
sub-lam-sap-gis-001 4a1f6aa1-ccab-4d40-ab30-cab8186900e0 Enabled

PS C:\Users\ankit>

Let me check on powershell module versions for Az.Accounts and Az.Subscription.

**Comment by mishraankit08** [comment]
2.16.0               Az.Accounts
Az.Subscription is not installed.

**Comment by msftphleiten** [comment]
can you please send me a short mail to phleiten@microsoft.com
I have a test version for you that might help you

**Comment by msftphleiten** [comment]
fixed with subscriptionid parameter
