### ISSUE TITLE
Latency tests not working

### ISSUE THREAD

**Issue by nicovd737** [Azure/SAP-on-Azure-Scripts-and-Utilities#23]
Hello,
Thanks a lot for your latency test script but i have an issue while running on my side.
All deployment is fine but when starting to run SSH command, it's all failed:

Remove-SSHTrustedHost: C:\Users\nbour\SAP-on-Azure-Scripts-and-Utilities\AvZone-Latency-Test\AvZone-Latency-Test.ps1:213
Line |
 213 |      Get-SSHTrustedHost | Remove-SSHTrustedHost
     |                           ~~~~~~~~~~~~~~~~~~~~~
     | The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters
     | that take pipeline input.

Creating SSH sessions
New-SSHSession: C:\Users\nbour\SAP-on-Azure-Scripts-and-Utilities\AvZone-Latency-Test\AvZone-Latency-Test.ps1:231
Line |
 231 |  … shsession = New-SSHSession -ComputerName $ipaddress -Credential $Cred …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

New-SSHSession: C:\Users\nbour\SAP-on-Azure-Scripts-and-Utilities\AvZone-Latency-Test\AvZone-Latency-Test.ps1:231
Line |
 231 |  … shsession = New-SSHSession -ComputerName $ipaddress -Credential $Cred …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

New-SSHSession: C:\Users\nbour\SAP-on-Azure-Scripts-and-Utilities\AvZone-Latency-Test\AvZone-Latency-Test.ps1:231
Line |
 231 |  … shsession = New-SSHSession -ComputerName $ipaddress -Credential $Cred …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Here are my modules with Powershell:

PS C:\Users\nbour\SAP-on-Azure-Scripts-and-Utilities\AvZone-Latency-Test> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.9.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.4.0                 Az.Compute                          {Add-AzContainerServiceAgentPoolProfile, Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent…}
Script     3.4.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, …
Script     2.5.1                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication…}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     1.4.7                 PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider…}
Manifest   2.3.0                 Posh-SSH                            {Get-SCPFile, Get-SCPFolder, Get-SCPItem, Get-SFTPFile…}
Script     2.2.4.1               PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability…}
Script     2.0.2                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}

I have tried also using directly powershell in Azure portal but same result.
Any idea of the problem ?

Thanks a lot

**Comment by msftphleiten** [comment]
Are you using PowerShell or PowerShell Core?
at the moment only PowerShell is supported.

**Comment by nicovd737** [comment]
Hello,
I'm using power 7.0.3

**Comment by msftphleiten** [comment]
could you please try version 5.1?

**Comment by nicovd737** [comment]
Works ! Thanks
