### ISSUE TITLE
Hana quality check script error

### ISSUE THREAD

**Issue by alishavez7** [Azure/SAP-on-Azure-Scripts-and-Utilities#30]
Hi Team,

I ran the Hana quality check script on a test sap vm and I am getting some error. 

I am getting the below output:

VM is running 🆗
VM not connected. 

VM is running fine and I am able to ssh the vm. Connection to azure resource manager api is fine. Could you please suggest if I am missing something. Thanks in advance.

**Comment by msftphleiten** [comment]
Which Powershell version are you running?
Is Posh-SSH visible using the command

`Get-Module -ListAvailable -Name Posh-SSH`

**Comment by alishavez7** [comment]
Hi Philipp,

Thanks for your response.

I have PS version 5.1 installed on my machine which required to run this script and i also have Posh-SSH module installed. Please refer the below details.

Version       
-------       
5.1.17763.1490

ModuleType  Version    Name                                                                                                                                 
---------- -------    ----                                                                                                                                     
Manifest        2.3.0      Posh-SSH  

Please suggest.

**Comment by msftphleiten** [comment]
any special SSH settings that you applied? ssh keys or password? allowing only certain SSH encryption mechanisms? any special hardening actions taken?

**Comment by alishavez7** [comment]
Hi Philipp,

We are using the username/password not the SSH Public/Private key pair for authentication and i am able to SSH the VM normally without any special special encryption config. There was no special hardening action taken.

However as i mentioned earlier, it's SUSE-SAP test VM with lower sku but at least this script should run and give the negative outputs. We could not run this script on Prod HANA server without performing the proper testing on a test server.


However its

**Comment by msftphleiten** [comment]
can you ping me on phleiten@microsoft.com
would love to investigate that with you.
