### ISSUE TITLE
Latency test Fails 

### ISSUE THREAD

**Issue by gopiii2000** [Azure/SAP-on-Azure-Scripts-and-Utilities#4]
When i did try to run the script , first it failed because it does'nt work on Mac.
Then i tried with WIndows and still i get error as failed to connect.

Running bandwidth and latency tests
Region:  westeurope
VM Type:  Standard_D4s_v3
Latency:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              | ping-vm02: failed to connect | ping-vm03: failed to connect |
| zone 2 | ping-vm01: failed to connect |              | ping-vm03: failed to connect |
| zone 3 | ping-vm01: failed to connect | ping-vm02: failed to connect |              |
-------------------------------------------------------

Bandwidth:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              | ping-vm02: failed to connect | ping-vm03: failed to connect |
| zone 2 | ping-vm01: failed to connect |              | ping-vm03: failed to connect |
| zone 3 | ping-vm01: failed to connect | ping-vm02: failed to connect |              |
-------------------------------------------------------

I checked the session seem to be connected but some how it fails to connect and that could be because the second command on qperf gives the below output 

Output     : {unable to bind to listen port}

**Comment by msftphleiten** [comment]
Hi gopiii2000
are you allowed to SSH to public IP addresses?
can you post the powershell command that you used?
