### ISSUE TITLE
QualityCheck.json - knownissues suse kernel - list of affected kernel incomplete

### ISSUE THREAD

**Issue by PeterPitterling** [Azure/SAP-on-Azure-Scripts-and-Utilities#41]
https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/blob/main/QualityCheck/QualityCheck.json#L656    
 
```
"KnownIssues": {
"SUSE": {
    "Kernel": [
	{
	    "MinVersion": "4.12.14-94.41.1",
	    "MaxVersion": "4.12.14-95.37.1",
	    "Description": "Please check SAP Note https://launchpad.support.sap.com/#/notes/2814271"
```

this is only covering SLES12.4 kernels .. the issue itself was also affecting higher sles releases which are not covered here

> SAP Note 2814271
> - SLES 12 SP4  - kernel version 4.12.14-95.37.1 (or higher)
> - SLES 12 SP5  - kernel version 4.12.14-122.7.1 (or higher)
> - SLES 15      - kernel version 4.12.14-150.38.1 (or higher)
> - SLES 15 SP1  - kernel version 4.12.14-197.21.1 (or higher)

I dont see any implementation how several ranges Min/Max for different SLES release should be listed ..

**Comment by msftphleiten** [comment]
You are correct, next version will include a OS / Distribution / Version dependency for the kernels

**Comment by PeterPitterling** [comment]
Good news, but why don't you keep this issue open until this new version has been merged to the repository?

**Comment by PeterPitterling** [comment]
Please re-open as this is still not fixed.

**Comment by msftphleiten** [comment]
we included the fix in V2, which is in private preview available here: https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/tree/QualityCheckV2/QualityCheck

I love customer feedback, would you be open for a 1:1 session where I should you the new version?
if you are interested please reach out to phleiten@microsoft.com

**Comment by msftphleiten** [comment]
will keep it open until we are GA with V2

**Comment by msftphleiten** [comment]
V2 is GA now
