### ISSUE TITLE
QualityCheck.json - net.ipv4.ip_local_port_range definition in conflict with SAP HANA recommendation

### ISSUE THREAD

**Issue by PeterPitterling** [Azure/SAP-on-Azure-Scripts-and-Utilities#42]
The NetApp recommendation is in conflict with the SAP HANA recommendation. In fact the SAP Host Agent will set the correct values, but only if this range is not defined within sysctl.conf.

```
{
    "Type": "OS",
    "Enabled": true,
    "RootRequired": true,
    "PreProcessingCommand": "",
    "ProcessingCommand": "sysctl net.ipv4.ip_local_port_range",
    "PostProcessingCommand": "",
    "ExpectedOutput": "net.ipv4.ip_local_port_range = 40000 65300",
    "ErrorMessage": "sysctl parameter missing or missconfigured",
    "HelpMessage": "see more details at https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-scale-out-standby-netapp-files-suse"
},
```

[2382421 - Optimizing the Network Configuration on HANA- and OS-Level](https://launchpad.support.sap.com/#/notes/2382421)

> net.ipv4.ip_local_port_range  => 9000-65499
> As HANA uses a considerable number of connections for the internal communication, it makes sense to have as many client ports available as possible for this purpose.
> At the same time, you need to ensure that you explicitly exclude the ports used by processes and applications which bind to specific ports by adjusting parameter net.ipv4.ip_local_reserved_ports accordingly.
> If configured correctly, the SAP Host Agent takes care of adjusting this parameter and setting it manually is neither recommended nor required.
> For further details about the SAP Host Agent please see the section below.
> The SAP Host Agent typically increases the port range typically to 9000-65499. If your port range is significantly different, for example when your lower port range starts with port 40000, please check the SAP Host Agent section below.

**Comment by msftphleiten** [comment]
Thanks Peter, I will discuss the issue with the team responsible for defining the parameters.

**Comment by PeterPitterling** [comment]
Please re-open as this is still not fixed.

In the meantime this section has been added

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-scale-out-standby-netapp-files-suse

>  Tip
> Avoid setting net.ipv4.ip_local_port_range and net.ipv4.ip_local_reserved_ports explicitly in the sysctl configuration files to allow SAP Host Agent to manage the port ranges. For more details see SAP note 2382421.

**Comment by msftphleiten** [comment]
included in new version, will keep it open until script is GA

**Comment by msftphleiten** [comment]
V2 is GA now
