### ISSUE TITLE
Move-VM-from-AvSet-to-AvZone

### ISSUE THREAD

**Issue by jotcoolguycapri** [Azure/SAP-on-Azure-Scripts-and-Utilities#5]
We were planning to move the servers from Availability sets to Availability zones and we used the  script.  It fails for us in the last step of network creation with the below error:

WARNING: Since the VM is created using premium storage or managed disk, existing standard storage account, drtestingdiag430, is used for boot diagnostics.
New-AzVM : Required parameter 'networkProfile' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'networkProfile' is missing (null).
ErrorTarget: networkProfile
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : b21f7648-d319-4937-b537-b474fdaa9eaf
At C:\Users\JYGEORG\Desktop\Move-VM-from-AvSet-to-AvZone.ps1:309 char:1
+ New-AzVM  -ResourceGroupName $ResourceGroupName -Location $originalVM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

Before this step they had asked to give inputs for :
Supply values for the following parameters:
(Type !? for Help.)
VM: vmapp2957
Id: /subscriptions/-----/resourceGroups/DRTesting/providers/Microsoft.Network/virtualNetworks/DRtestingVN
Add-AzVMNetworkInterface : Cannot bind parameter 'VM'. Cannot convert the "vmapp2957" value of type "System.String" to type 

We tried providing the VM name , Network name and also the nic id but all filed. C

As a result other steps are completed and also the primary VM gets deleted. The new VM is not created as this fails.

Kindly let us know how to proceed on this.

**Comment by KimForss** [comment]
I just reran the script and I had no issues. Can you run Get-Module in your powershell windows and share the output.

**Comment by jotcoolguycapri** [comment]
Please find the result below:
![image](https://user-images.githubusercontent.com/51259567/86801711-f4ea2d00-c091-11ea-80ff-b5850ae5a8b8.png)

**Comment by KimForss** [comment]
Mine are the same. I added a new version with more logging.
Can you run it with -Verbose to see if there is more information on why it fails
