### ISSUE TITLE
ANF storage check is not working.

### ISSUE THREAD

**Issue by alishavez7** [Azure/SAP-on-Azure-Scripts-and-Utilities#51]
Hi Team,

We ran the quality check script on one of our HANA system and noticed that this script is unable to fetch the ANF volume details, we are getting the below error.

Starting Storage Checks
--------------------------------------------
 ERROR - Something went wrong
 ERROR - File System /hana/data - please check mount options
 ERROR - File System /hana/data not mounted
 ERROR - File System /hana/log - please check mount options
 ERROR - File System /hana/log not mounted
 ERROR - File System /hana/shared - please check mount options
 ERROR - File System /hana/shared not mounted
--------------------------------------------
Ending Storage Checks

DB is up and running and DB ANF volumes are mounted properly. Could you please check and update

**Comment by goraco** [comment]
hi
script is not handling ANF volumes. 

You need to configure automatically mounting of ANF volumes inside of Linux OS.

Of course , mount option and path must be correct 

as long as you configure this inside OS properly, expectation is that scripts will work transparently 


best

**Comment by msftphleiten** [comment]
as discussed offline the issue is that you are using different type of mount points, you have to change it in the json file.
next version is planned to have a type of autodetect, if technically possible

**Comment by msftphleiten** [comment]
seems there is a problem with multiple ANF pools in one account

**Comment by msftphleiten** [comment]
V2 includes fixes
