### ISSUE TITLE
TCP Settings only checked for ANF storage & tcp_timestamps confusion

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#60]
Hello.

The Linux TCP param checks are only executed if ANF is used.
If ANF is not used, no TCP param checks are done.

Would be good to have a check against things like "tcp_timestamps", expecially if the VM sits behind a Load Balancer.
When the VM sits behind a Load Balancer then "tcp_timestamps" must be "0" according to the docs.

However, when the VM is using ANF for HANA storage then the script is checking "tcp_timestamps" has a value of "1".  But this value is needed only when HANA has a scale-out with a standby node and using ANF.

Darryl

**Comment by msftphleiten** [comment]
we are publishing a new release in the next weeks, you can already use the preview available here:
https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/tree/QualityCheckV2/QualityCheck

it will check DB, App and ASCS servers and tcp_timestamps=0 will be used for all HA scenarios (DB & ASCS)
