### ISSUE TITLE
stonith-timeout check mismatch with docs

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#62]
Hello.

Cluster param: "stonith-timeout" in the docs here:  [https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker)

Is suggesting 900s.
In the qualitycheck v2 it is looking for 144s.

As a side note, the crm command can be used to check the value like so:  `crm configure get_property stonith-timeout`

Darryl

**Comment by msftphleiten** [comment]
you are correct, there are actually two values documented.
for SBD it is 144s
for Fencing Agent it is 900
I will split the check into SBD and fencing

**Comment by msftphleiten** [comment]
updated and split SBD and FencingAgent check
