### ISSUE TITLE
net.ipv4.tcp_keepalive_time = 120

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#63]
Hello,

I'm struggling to find which document contains the recommendation for "net.ipv4.tcp_keepalive_time = 120" as per the QualityCheck v2.
All docs that I have checked show a value of 300.

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-netapp-files
https://docs.microsoft.com/en-gb/azure/virtual-machines/workloads/sap/high-availability-guide-suse-nfs-azure-files
SAP note 1410736.

Is there an internal note on this setting value?

Thanks

Darryl

**Comment by msftphleiten** [comment]
There is no SAP about that until now, we have seen that this value is important for app servers in case of HA failover on ASCS side
