### ISSUE TITLE
Recommendations for net.ipv4.tcp_retries2

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#64]
Hello.

The QualityCheck v2 is looking for "net.ipv4.tcp_retries2 = 3".
According to the SUSE document here:  https://www.suse.com/support/kb/doc/?id=000019722
(created 21-Oct-2021).
A value of less than 8 will go against the recommendations of RFC 1122.

That same document shows a default value for "net.ipv4.tcp_retries1 = 3" (retries1), is there some confusion between retries1 and retries2 settings ?   or are we saying that they both need to be "3", against what the SUSE KB is recommending?

Thanks

**Comment by msftphleiten** [comment]
yes, this seems to be a new note, I will discuss it internally.
the note doesn't prohibit to decrease the value and it mentions that decreasing the value might solve an issue.

**Comment by msftphleiten** [comment]
updated according to SUSE notes
