### ISSUE TITLE
New feature request: Accelerated Networking - check if enabled for SAP

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#65]
Hello

I've got a couple of SAP VMs which should have Accelerated Networking enabled but don't.
Would be good to have this checked in the QualityCheck v2.

The CollectNetworkInterfaces function collects the info, but I can't see it being checked in the execution of the check.
It just puts the value out in the HTML results but doesn't draw attention to it.
I believe for HANA it is a requirement?

As a side note:
- There's a small typo in the powershell script HTML output "a" tag:  "Network Interfaes"
- There's a small typo in one of the output text elements of the JSON file:  "Takerover"

Thanks.

**Comment by msftphleiten** [comment]
added check for accelerated networking
