### ISSUE TITLE
Support of File Ext4 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [Azure/SAP-on-Azure-Scripts-and-Utilities#69]
Hi Team,

i do have my test box running with Ext4, looks like Ext file type of structure is not supported. Any plan to add it ? some of simple 2 Tier setup, does not necessary run with LVM. 

the error message what I can see is  "Please check your parameters, HANA directories not found."

Best Regards

Chan Jin

**Comment by msftphleiten** [comment]
ext4 is not supported for HANA workloads, only xfs is supported from Microsoft side to run HANA workloads
I will think about a different message/test to incorporate that

please see https://launchpad.support.sap.com/#/notes/2972496

**Comment by msftphleiten** [comment]
version 2022011001 of quality check adds support for misconfigured "ext4" filesystems and will show it as error, but run the script
