### ISSUE TITLE
Mellanox hv_storvsc - how to change

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#70]
Hello,

The mellanox settings check output from the JSON is suggesting the values are set with sysctl:

_"set hv_storvsc.storvsc_ringbuffer_size=131072 and hv_storvsc.storvsc_vcpus_per_sub_channel=1024 in sysctl.conf"_

They must be set with Kernel boot options (grub) as mentioned here:  https://www.suse.com/support/kb/doc/?id=000020248

Darryl

**Comment by msftphleiten** [comment]
thank you!
fixed in version 202201110144
