### ISSUE TITLE
AvZone-Latency-Test.ps1 | Invoke-SSHCommand Fails to Connect

### ISSUE THREAD

**Issue by cocallaw** [Azure/SAP-on-Azure-Scripts-and-Utilities#72]
### Issue
When running the script, it fails when trying to connect SSH sessions to start install of qperf and run tests.

Script was run using command 
`./AvZone-Latency-Test.ps1 -Region eastus2 -SubscriptionName cocallawXXXXX`

The VMs and Networking resources are successfully created, when the script runs Invoke-SSHCommand an excpetion is generated because it is unable to connect to the VM.

`Invoke-SSHCommand : Unable to connect session to 104.45.XXX.XXX :: Exception calling "Connect" with "0" argument(s):
"Connection failed to establish within 10000 milliseconds."`

As a result, the remaining script fails since it is unable to perform any actions against the Azure VMs deployed.

### Environment 
PowerShell Version 5.1
Posh-SSH Version 3.0.0 & 2.0.2
Windows 11 

### Output
Creating SSH sessions
WARNING: Host key is not being verified since Force switch is used.
WARNING: Host key is not being verified since Force switch is used.
WARNING: Host key is not being verified since Force switch is used.
Getting Hosts for virtual machines
Invoke-SSHCommand : Unable to connect session to 104.45.XXX.XXX :: Exception calling "Connect" with "0" argument(s):
"Connection failed to establish within 10000 milliseconds."
At C:\Source\Github\AzRegion-Latency-Test\AvZone-Latency-Test.ps1:241 char:19
+ ...   $output = Invoke-SSHCommand -Command "cat /var/lib/hyperv/.kvp_pool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SSHCommand

VM1 :
Invoke-SSHCommand : Unable to connect session to 20.120.XXX.XXX :: Exception calling "Connect" with "0" argument(s): "Connection
failed to establish within 10000 milliseconds."
At C:\Source\Github\AzRegion-Latency-Test\AvZone-Latency-Test.ps1:241 char:19
+ ...   $output = Invoke-SSHCommand -Command "cat /var/lib/hyperv/.kvp_pool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SSHCommand

VM2 :
Invoke-SSHCommand : Unable to connect session to 40.70.XXX.XXX :: Exception calling "Connect" with "0" argument(s): "Connection
failed to establish within 10000 milliseconds."
At C:\Source\Github\AzRegion-Latency-Test\AvZone-Latency-Test.ps1:241 char:19
+ ...   $output = Invoke-SSHCommand -Command "cat /var/lib/hyperv/.kvp_pool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SSHCommand

VM3 :
Installing qperf on all VMs
Invoke-SSHCommand : Unable to connect session to 104.45.XXX.XXX :: Exception calling "Connect" with "0" argument(s):
"Connection failed to establish within 10000 milliseconds."
At C:\Source\Github\AzRegion-Latency-Test\AvZone-Latency-Test.ps1:253 char:23
+ ...   $output = Invoke-SSHCommand -Command "echo $VMLocalAdminPassword |  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SSHCommand

**Comment by msftphleiten** [comment]
Most of the issues are due to firewalls blocking SSH access to public IP addresses.
can you open PuTTY and access the public IP address directly?

you can use an existing subnet by specifying the paramter and "UsePublicIPAdress" set to false, then it will connect with internal IP addresses

**Comment by cocallaw** [comment]
@msftphleiten After the failure on the Invoke-SSHCommand  to get the VM hosts, I am able to stop the script and SSH to the VMs using their public IP address

I am currently testing with different PowerShell configurations to see if there is a change.

**Comment by msftphleiten** [comment]
updated the script to support PowerShell 7.1 or newer as well as Centos 8.4 to get a newer OS
