### ISSUE TITLE
Getting error for Redhat Linux

### ISSUE THREAD

**Issue by debi74** [Azure/SAP-on-Azure-Scripts-and-Utilities#74]
Hello,

Thanks for this nice utility script. When I ran this script for SUSE Linux, it ran successfully. But when I ran it for Redhat Linux, I got below error :

InvalidOperation: K:\dpp\utility\QualityCheck\QualityCheck.ps1:1140
Line |
1140 |          if ($_filesystem_hana.Source.StartsWith("/dev/sd")) {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: K:\dpp\utility\QualityCheck\QualityCheck.ps1:1237
Line |
1237 |          if ($_filesystem_hana.Source.StartsWith("/dev/sd")) {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: Cannot compare "System.Int32" because it is not IComparable.

Can you please let me know if I am doing any mistake ?

Thanks,
Debi Prasad

**Comment by msftphleiten** [comment]
Hi Debi,
would you mind sharing more details?
Which RH release? Which storage are you using? Are you using striping?
Can you share the command that you ran?
It would be perfect if you can send the the HTML file (if already there) and a sosreport to phleiten@microsoft.com
Thanks Philipp

**Comment by debi74** [comment]
Hi Philipp,

Please find my answer below :

Which RH release? -> RHEL 8.4
Which storage are you using? -> Standard SSD
Are you using striping? -> No


The below command I ran :
.\QualityCheck.ps1 -VMOperatingSystem RedHat -VMDatabase HANA -VMRole DB
-AzVMResourceGroup rg_dev_sap -AzVMName vm-dev-bauhana-001 -VMHostname
192.168.88.70 -VMUsername bauhanaadmin -VMConnectionPort 6037 -DBDataDir
/hana/data/HED -DBLogDir /hana/log/HED -DBSharedDir /hana/shared/HED
-Hardwaretype VM

Please find the attached HTML reports.


Thanks
Debi Prasad

**Comment by msftphleiten** [comment]
Thank you for the files, seems all your checks that require root rights can't be executed.
can you please try to logon to your system using e.g. putty and try sudo command?
are you asked for a password?

**Comment by debi74** [comment]
Hi Philipp,

Yes, after logon to the system, if I execute sudo -i, I need to put the
password again.

BTW, both the passwords are the same.

Thanks,
Debi Prasad

**Comment by msftphleiten** [comment]
issue should be solved in version 2022021101
thank you for your support!

**Comment by debi74** [comment]
Welcome. It looks much better now!!!
