### ISSUE TITLE
kernel parameter checks error + one recommendation

### ISSUE THREAD

**Issue by iklema** [Azure/SAP-on-Azure-Scripts-and-Utilities#75]
Hello there,

First of all Thank you very much for such helpful tool, great job!

We have an issue/error with 2 checks:
**APP-OS-0005:**
running SUSE 15 SP3
according what i found this kernel parameter (tcp_tw_recycle) was removed from Kernel 4.12 so it's obsolete check for higher kernels. 

**APP-OS-0007**
net.ipv4.tcp_retries1 = 3
Even we have it set correctly it's showing Error.

**Recommendation:**
Maybe more valid output for linux systems running SystemD would be "systemctl list-unit-files --state=enabled" instead of chkconfig (this check makes more sense for old linux with systemV)

In case some more info needed please let me know.
Thank you!
Kind regards,
Igor

**Comment by msftphleiten** [comment]
Thank you Igor, I will circle back with the team and come back

**Comment by msftphleiten** [comment]
issues fixed in 2022013002
