### ISSUE TITLE
AvZone-Latency-Test done for UKSOUTH for SAP project but output error

### ISSUE THREAD

**Issue by jphilip2190** [Azure/SAP-on-Azure-Scripts-and-Utilities#78]
HI,

We had a project on SAP for where as per our requirement we wanted to teat Latency/Bandwidth for UKSouth Zones as per the script we  had edited and applied but the Latency and Bandwidth result has not been shown,

**Can some one help me to resolve the issue.**

PS C:\>
PS C:\>
PS C:\> .\apps\sapcar\AvZone-Latency-Test.ps1 -SubscriptionName sub-aws-sap-nprd-01 -region UKSouth -testtool niping -nipingpath "CC:\apps\sapcar\niping.exe"

Name                                     Account                           SubscriptionName                  Environment                       TenantId
----                                     -------                           ----------------                  -----------                       --------
sub-aws-sap-nprd-01 (ceef8efe-cb3c-4dee… A_jMavelith@anglianwater.onmicro… sub-aws-sap-nprd-01               AzureCloud                        e7ba1d02-2aa2-48d5-8185-e3dc6bf7…
Creating resource group
Creating vNET and Subnet
Creating NSG
Creating VMs
All jobs created, waiting ...

HasMoreData          : True
Location             : localhost
StatusMessage        : Completed
CurrentPSTransaction :
Host                 : System.Management.Automation.Internal.Host.InternalHost
Command              : New-AzVM
JobStateInfo         : Completed
Finished             : System.Threading.ManualResetEvent
InstanceId           : 9db8e2ab-bd4e-4b54-8136-04bcc1e281e6
Id                   : 1
Name                 : Long Running Operation for 'New-AzVM'
ChildJobs            : {}
PSBeginTime          : 03-03-2022 4.26.10 PM
PSEndTime            : 03-03-2022 4.27.05 PM
PSJobTypeName        : AzureLongRunningJob`1
Output               : {Microsoft.Azure.Commands.Compute.Models.PSAzureOperationResponse}
Error                : {}
Progress             : {}
Verbose              : {}
Debug                : {[AzureLongRunningJob]: Starting cmdlet execution, setting for cmdlet confirmation required: 'False', [AzureLongRunningJob]: Completing cmdlet execution
                       in RunJob}
Warning              : {}
Information          : {}
State                : Completed

HasMoreData          : True
Location             : localhost
StatusMessage        : Completed
CurrentPSTransaction :
Host                 : System.Management.Automation.Internal.Host.InternalHost
Command              : New-AzVM
JobStateInfo         : Completed
Finished             : System.Threading.ManualResetEvent
InstanceId           : f1145c47-8b47-4bd0-a608-2a6566bfcb0e
Id                   : 2
Name                 : Long Running Operation for 'New-AzVM'
ChildJobs            : {}
PSBeginTime          : 03-03-2022 4.26.35 PM
PSEndTime            : 03-03-2022 4.27.34 PM
PSJobTypeName        : AzureLongRunningJob`1
Output               : {Microsoft.Azure.Commands.Compute.Models.PSAzureOperationResponse}
Error                : {}
Progress             : {}
Verbose              : {}
Debug                : {[AzureLongRunningJob]: Starting cmdlet execution, setting for cmdlet confirmation required: 'False', [AzureLongRunningJob]: Completing cmdlet execution
                       in RunJob}
Warning              : {}
Information          : {}
State                : Completed

HasMoreData          : True
Location             : localhost
StatusMessage        : Completed
CurrentPSTransaction :
Host                 : System.Management.Automation.Internal.Host.InternalHost
Command              : New-AzVM
JobStateInfo         : Completed
Finished             : System.Threading.ManualResetEvent
InstanceId           : 0af01eb7-3754-4b88-b67e-65f67e422a8b
Id                   : 3
Name                 : Long Running Operation for 'New-AzVM'
ChildJobs            : {}
PSBeginTime          : 03-03-2022 4.27.00 PM
PSEndTime            : 03-03-2022 4.27.57 PM
PSJobTypeName        : AzureLongRunningJob`1
Output               : {Microsoft.Azure.Commands.Compute.Models.PSAzureOperationResponse}
Error                : {}
Progress             : {}
Verbose              : {}
Debug                : {[AzureLongRunningJob]: Starting cmdlet execution, setting for cmdlet confirmation required: 'False', [AzureLongRunningJob]: Completing cmdlet execution
                       in RunJob}
Warning              : {}
Information          : {}
State                : Completed

All jobs completed

ResourceGroupName        : AvZoneLatencyTest
Id                       : /subscriptions/ceef8efe-cb3c-4dee-8a82-c9e8c8b081ef/resourceGroups/AvZoneLatencyTest/providers/Microsoft.Compute/virtualMachines/azping-vm01
VmId                     : 2b0a71eb-0307-472a-918c-53a1c6146655
Name                     : azping-vm01
Type                     : Microsoft.Compute/virtualMachines
Location                 : uksouth
ExtendedLocation         :
LicenseType              :
Tags                     : {}
AvailabilitySetReference :
DiagnosticsProfile       :
Extensions               : {}
HardwareProfile          : Microsoft.Azure.Management.Compute.Models.HardwareProfile
InstanceView             :
NetworkProfile           : Microsoft.Azure.Management.Compute.Models.NetworkProfile
SecurityProfile          :
OSProfile                : Microsoft.Azure.Management.Compute.Models.OSProfile
BillingProfile           :
Plan                     :
ProvisioningState        : Succeeded
StorageProfile           : Microsoft.Azure.Management.Compute.Models.StorageProfile
DisplayHint              : Compact
Identity                 :
Zones                    : {1}
FullyQualifiedDomainName :
AdditionalCapabilities   :
ProximityPlacementGroup  :
Host                     :
VirtualMachineScaleSet   :
EvictionPolicy           :
Priority                 :
HostGroup                :
CapacityReservation      :
UserData                 :
ApplicationProfile       :
PlatformFaultDomain      :
RequestId                : 781b24fc-eb98-49b8-a012-fe7b2b930647
StatusCode               : OK

ResourceGroupName        : AvZoneLatencyTest
Id                       : /subscriptions/ceef8efe-cb3c-4dee-8a82-c9e8c8b081ef/resourceGroups/AvZoneLatencyTest/providers/Microsoft.Compute/virtualMachines/azping-vm02
VmId                     : b47ecbfc-1f0a-4c2b-92be-b596e8f0e65a
Name                     : azping-vm02
Type                     : Microsoft.Compute/virtualMachines
Location                 : uksouth
ExtendedLocation         :
LicenseType              :
Tags                     : {}
AvailabilitySetReference :
DiagnosticsProfile       :
Extensions               : {}
HardwareProfile          : Microsoft.Azure.Management.Compute.Models.HardwareProfile
InstanceView             :
NetworkProfile           : Microsoft.Azure.Management.Compute.Models.NetworkProfile
SecurityProfile          :
OSProfile                : Microsoft.Azure.Management.Compute.Models.OSProfile
BillingProfile           :
Plan                     :
ProvisioningState        : Succeeded
StorageProfile           : Microsoft.Azure.Management.Compute.Models.StorageProfile
DisplayHint              : Compact
Identity                 :
Zones                    : {2}
FullyQualifiedDomainName :
AdditionalCapabilities   :
ProximityPlacementGroup  :
Host                     :
VirtualMachineScaleSet   :
EvictionPolicy           :
Priority                 :
HostGroup                :
CapacityReservation      :
UserData                 :
ApplicationProfile       :
PlatformFaultDomain      :
RequestId                : 781b24fc-eb98-49b8-a012-fe7b2b930647
StatusCode               : OK

ResourceGroupName        : AvZoneLatencyTest
Id                       : /subscriptions/ceef8efe-cb3c-4dee-8a82-c9e8c8b081ef/resourceGroups/AvZoneLatencyTest/providers/Microsoft.Compute/virtualMachines/azping-vm03
VmId                     : 73908018-cee1-44d2-a1f0-e3dded05af79
Name                     : azping-vm03
Type                     : Microsoft.Compute/virtualMachines
Location                 : uksouth
ExtendedLocation         :
LicenseType              :
Tags                     : {}
AvailabilitySetReference :
DiagnosticsProfile       :
Extensions               : {}
HardwareProfile          : Microsoft.Azure.Management.Compute.Models.HardwareProfile
InstanceView             :
NetworkProfile           : Microsoft.Azure.Management.Compute.Models.NetworkProfile
SecurityProfile          :
OSProfile                : Microsoft.Azure.Management.Compute.Models.OSProfile
BillingProfile           :
Plan                     :
ProvisioningState        : Succeeded
StorageProfile           : Microsoft.Azure.Management.Compute.Models.StorageProfile
DisplayHint              : Compact
Identity                 :
Zones                    : {3}
FullyQualifiedDomainName :
AdditionalCapabilities   :
ProximityPlacementGroup  :
Host                     :
VirtualMachineScaleSet   :
EvictionPolicy           :
Priority                 :
HostGroup                :
CapacityReservation      :
UserData                 :
ApplicationProfile       :
PlatformFaultDomain      :
RequestId                : 781b24fc-eb98-49b8-a012-fe7b2b930647
StatusCode               : OK

Waiting for four minute for all systems to come up ...
WARNING: No known host file found, C:\Users\jmavelit\.poshssh\hosts.json
Creating SSH sessions
WARNING: Host key is not being verified since Force switch is used.
WARNING: Host key is not being verified since Force switch is used.
WARNING: Host key is not being verified since Force switch is used.
Getting Hosts for virtual machines
VM1 : LON241080120035
VM2 : LON261060606031
VM3 : LON230101130842
Installing niping on all VMs
Running bandwidth and latency tests
Region:  UKSouth
VM Type:  Standard_D8s_v3
Latency:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              |              |              |
| zone 2 |              |              |              |
| zone 3 |              |              |              |
-------------------------------------------------------

Bandwidth:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              |       0 MB/s |       0 MB/s |
| zone 2 |       0 MB/s |              |       0 MB/s |
| zone 3 |       0 MB/s |       0 MB/s |              |
-------------------------------------------------------
Deleting Resource Group
True

PS C:\>

**Comment by msftphleiten** [comment]
Thank you for using the script.
The VMs are running linux and you need to provide the linux version of niping using an http/https link.
BR

**Comment by jphilip2190** [comment]
Hi,
Can you explain me in detail with some reference URL on below point,

**you need to provide the linux version of niping using an http/https link.**

**Comment by msftphleiten** [comment]
you can e.g. use an Azure blob storage to upload the the executable, the system will then download it from this link, e.g. somethink like https://yourstorageaccount/niping
as an alternative you can the builtin qperf solution to get latency and throughput.

**Comment by jphilip2190** [comment]
ok,
but in my current situation i am running from local workstation with the nipping script kept on my local drive , will this not work?? or its mandatory to store it on Blob storage

AvZone-Latency-Test.ps1 -SubscriptionName sub-aws-sap-nprd-01 -region UKSouth -testtool niping -nipingpath "CC:\apps\sapcar\niping.exe"

2. ok from where will i get linux version of niping?

**Comment by msftphleiten** [comment]
you have to download the SAP Linux executables from marketplace to get niping for Linux

at the moment the file is not copied from the VM to the server but downloaded through a weblink, let me think about adding that option for niping

**Comment by jphilip2190** [comment]
Thanks Sir Its working Now... appreciated your quick response
