### ISSUE TITLE
AvZone-Latency-Test fails due to storage account

### ISSUE THREAD

**Issue by elestedt** [Azure/SAP-on-Azure-Scripts-and-Utilities#79]
AvZone-Latency-Test makes assumptions about storage accounts, which causes

> Provisioning failed. Storage account '<snip>' is of Standard_ZRS type. Boot Diagnostics supports Standard_GRS,Standard_LRS,Standard_RAGRS storage account types.. StorageAccountTypeNotSupported

This should either be created by the script or be configurable.

**Comment by msftphleiten** [comment]
thanks for reaching out.
can you please paste a screenshot if your issue as well as the command you were running?

**Comment by elestedt** [comment]
Since it deleted everything I can't show the screenshot - that the failure message from the VM. The script just silently fails when trying to do SSH connections. And on that note - maybe the script should fail if it could not make all three ssh connections instead of continuing?

Command (with sub specific things removed/changed
> .\AvZone-Latency-Test.ps1 -SubscriptionName subname -region westeurope -UsePublicIPAddresses $false -UseExistingVnet $true -NetworkName vnetname -ResourceGroupNameNetwork vnetrg -ResourceGroupName AvZoneLatencyTest -SubnetName AvZoneLatencyTest

**Comment by elestedt** [comment]
To work around the issue I created a storage account with one of the indicated types, with a name that ensures it's at the top of the list. It's an ugly workaround though - that the script won't clean up.

**Comment by msftphleiten** [comment]
fixed it in new version
