### ISSUE TITLE
AvZone-Latency-Test.ps1

### ISSUE THREAD

**Issue by jkirkmannz** [Azure/SAP-on-Azure-Scripts-and-Utilities#81]
Errors on the latest version, using the code from the previous version works OK.
InvalidArgument: /home/xxxxx/latency.ps1:251
Line |
 251 |              $ipaddresses[$ComputerName] += $networkinterfaceconfig.Pr …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "azping-vm01" to type "System.Int32". Error: "Input string was not in a correct format."

MethodInvocationException: /home/xxxxx/latency.ps1:306
Line |
 306 |              $latencytemp = $latencytemp.substring($latencytemp.IndexO …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Substring" with "1" argument(s): "startIndex cannot be larger than length of string. (Parameter 'startIndex')"

**Comment by msftphleiten** [comment]
Hi,
thanks for bringing this up, there was a type, instead of @{} in ipaddresses there was @() 
that's why the hashtable didn't work.
