### ISSUE TITLE
$ipaddresstoping2 variable  is being used without defining.

### ISSUE THREAD

**Issue by veeresh-490** [Azure/SAP-on-Azure-Scripts-and-Utilities#82]
# run performance tests
        Write-Host -ForegroundColor Green "Running bandwidth and latency tests"
        For ($zone=1; $zone -le $zones; $zone++) {

            $vmtopingno1 = (( $zone   %3)+1)
            $vmtoping1 = $VMPrefix + (( $zone   %3)+1)
            $ipaddresstoping1 = $ipaddresses[$vmtoping1]
            $vmtopingno2 = ((($zone+1)%3)+1)
            $vmtoping2 = $VMPrefix + ((($zone+1)%3)+1)
            **$ipaddresstoping1 = $ipaddresses[$vmtoping2]**  
# Guess variable name defined incorrectly.  Please confirm if this is not a issue. 
in  below section $ipaddresstoping2 is being used but, not defined anywhere. Please check

     $output = Invoke-SSHCommand -Command "qperf $ipaddresstoping2 tcp_lat" -SessionId $sshsessions[$zone-1].SessionId
            $latencytemp = [string]$output.Output[1]
            $latencytemp = $latencytemp.substring($latencytemp.IndexOf("=")+3)
            $latencytemp = $latencytemp.PadLeft(12)
            $latency[$zone -1][$vmtopingno2 -1] = $latencytemp

            $output = Invoke-SSHCommand -Command "qperf $ipaddresstoping2 tcp_bw" -SessionId $sshsessions[$zone-1].SessionId
            $bandwidthtemp = [string]$output.Output[1]
            $bandwidthtemp = $bandwidthtemp.substring($bandwidthtemp.IndexOf("=")+3)
            $bandwidthtemp = $bandwidthtemp.PadLeft(12)
            $bandwidth[$zone -1][$vmtopingno2 -1] = $bandwidthtemp

**Comment by msftphleiten** [comment]
thanks for reaching out, I patched the version, please try again

**Comment by veeresh-490** [comment]
@msftphleiten Thank you for the response. Please update variable declaration for qperf  block as well, now is update only for nipping tool block

I am getting output as below for qperf tests.  Script giving output for either $ipaddresstoping1 or $ipaddresstoping2(giving results for only one machine in a loop and for second machine getting error as failed to connect)  in a run. 

I am using using private IP and public IP is disabled. Please check what could be the error. 
Please mention what ports should be enabled.

Latency:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              |      7.83 us | .xx.xx.xx: failed to connect |
| zone 2 | .xx.xx.xx: failed to connect |              |      7.92 us |
| zone 3 |      7.81 us | .xxx.xx.xx: failed to connect |              |
-------------------------------------------------------

Bandwidth:
         ----------------------------------------------
         |    zone 1    |    zone 2    |    zone 3    |
-------------------------------------------------------
| zone 1 |              |   5.2 GB/sec | .xx.xx.xx: failed to connect |
| zone 2 | .xxx.xx.xx: failed to connect |              |  6.78 GB/sec |
| zone 3 |  5.39 GB/sec | .xx.xx.xx: failed to connect |              |
------------------------------------------------------

**Comment by veeresh-490** [comment]
@msftphleiten  I am running this tests for suse linux. Please confirm if this script works for suse linux.

**Comment by msftphleiten** [comment]
@veeresh-490  can you please share the command that you are running?
do you mean you are changed the script to run SUSE VMs or you are starting it from SUSE?

**Comment by veeresh-490** [comment]
@msftphleiten I am running this script for existing SUSE vm's. I already have vms created in subnet

**Comment by msftphleiten** [comment]
I'm sorry, but I can't support manually deployed VMs, you can run the qperf commands manually to get your results.
Please let me know if you have issues running the script with VMs created by the script.

**Comment by veeresh-490** [comment]
Sure. Thank you @msftphleiten.  There is a parameter ($UseExistingVMs) to run the tests for the existing virtual machines. Hence, I gave it a try. 
Anyway, Thanks for the confirmation

**Comment by msftphleiten** [comment]
no problem, this flag is for scenarios where you want to run multiple tests with one set of VMs

**Comment by veeresh-490** [comment]
@msftphleiten
Ok one last doubt.  We have created 3 virtual machines in westeurope region in different available zones.  And all vms are in same RG and same subnet.  Now, If I change $UseExistingVMs flag to true and pass values to existing  vnet, subnet parameters,  Will script gives the test results ?

**Comment by msftphleiten** [comment]
if the VMs have the names that are defined in the script, sudo works as expected, then yes.
