### ISSUE TITLE
Each zone connects to only on IP address in another zone

### ISSUE THREAD

**Issue by kirhie** [Azure/SAP-on-Azure-Scripts-and-Utilities#83]
$vmtopingno1 = (( $zone   %3)+1)
            $vmtoping1 = $VMPrefix + (( $zone   %3)+1)
            $ipaddresstoping1 = $ipaddresses[$vmtoping1]
            $vmtopingno2 = ((($zone+1)%3)+1)
            $vmtoping2 = $VMPrefix + ((($zone+1)%3)+1)
            **_$ipaddresstoping1 = $ipaddresses[$vmtoping2]_**

The above line of code overwrites the _ipaddresstoping1_ and VM in one zone connects to only one VM from another 2 zones.
Possible fix would be:

            **_$ipaddresstoping2 = $ipaddresses[$vmtoping2]_**

**Comment by msftphleiten** [comment]
got fixed, was overwritten and is fixed again :-)
thanks for bringing it up
