### ISSUE TITLE
VMPassword should NOT be $Mandatory as it isn't necessary when using SSH key and root or an account with passwordless sudo

### ISSUE THREAD

**Issue by spoelstraethan** [Azure/SAP-on-Azure-Scripts-and-Utilities#84]
It is also painful to pass the value from an environment variable, eg to fetch the value of a `secure variable` in an Azure DevOps pipeline.

     .\QualityCheck.ps1 -VMOperatingSystem RedHat -VMDatabase HANA `
        -VMRole APP -AzVMResourceGroup $env:ResourceGroupName `
        -AzVMName $env:AzVMName -VMHostname $env:VMHostname `
        -VMUsername $env:VMUsername `
        -VMPassword $(ConvertTo-SecureString $env:VMPassword -AsPlainText -Force) `
        -SSHKey $env:PathToSSHKeyFile

**Comment by msftphleiten** [comment]
thanks @spoelstraethan for reaching out, I think there are multiple ways that reflect the different scenarios and beginning of June the SSH key parameters will be refined.

I'm thinking about

- User/Password (as today)
- User/Password/SSH key file without password --> user password would be required for sudo commands
- User/Password/SSH key file/SSH key file password

do you require a password when using sudo or are you running a nopasswd sudo config?

**Comment by spoelstraethan** [comment]
Currently we are using an SSH private key with public key in the `~root/.ssh/authorized_keys` of remote hosts to perform management tasks in case of any issues with `sudo` looking up domain users and groups. This key lives in the `root` account on a secure jump/bastion host and requires a user request temporary root access to utilize it. It doesn't currently have a passphrase required for the private key, but that is something we may add in the future.

We try to avoid passwordless sudo if possible, so we require the domain user's password before they perform any root tasks to ensure it isn't locked out or deactivated, as well as validate their account is currently a member of the temporary "rootaccess" sudoers AD group. We also control access to collections of hosts by only allowing members of the "app team" to access hosts "owned" by that team, so that is where our jump host with access to all hosts regardless of team became required to utilize the QualityCheck script effectively.

**Comment by msftphleiten** [comment]
version 2022070301 has new options which are in preview at the moment, you can try it if you want,
you would use the flag -LogonAsRootSSHKey
