### ISSUE TITLE
QualityCheck.json - HDB-ANF-* checks

### ISSUE THREAD

**Issue by PeterPitterling** [Azure/SAP-on-Azure-Scripts-and-Utilities#85]
OS tcp parameters have been recently updated
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-scale-out-standby-netapp-files-suse

- not required any longer
HDB-ANF-0003
HDB-ANF-0004
HDB-ANF-0005

- to be adjusted
HDB-ANF-0006
HDB-ANF-0007

**Comment by msftphleiten** [comment]
Thanks Peter, I'm already working on it

**Comment by msftphleiten** [comment]
updated in version 2022070301
