### ISSUE TITLE
Error - SSH - Incorrrecect Credentials

### ISSUE THREAD

**Issue by suhasprabhu680** [Azure/SAP-on-Azure-Scripts-and-Utilities#89]
Hello,

I am trying to use the MultiRun functionality for 2 VMs hosted in Azure. Both the servers have same password. I am executing the script via powershell 7.2.5 on a Windows 11 VDI. But i get below error -

ERROR    - SSH - Please check your credentials, unable to logon
Invoke-SSHCommand: C:\Users\nxf88094\Downloads\scripts\scripts\QualityCheck\QualityCheck.ps1:982
Line |
 982 |  …  = Invoke-SSHCommand -Command $_command -SessionId $script:_SessionID
     |                                                       ~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'SessionId' because it is null.

Invoke-SSHCommand: C:\Users\nxf88094\Downloads\scripts\scripts\QualityCheck\QualityCheck.ps1:982
Line |
 982 |  …  = Invoke-SSHCommand -Command $_command -SessionId $script:_SessionID
     |                                                       ~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'SessionId' because it is null.

Set-Variable: Missing an argument for parameter 'Value'. Specify a parameter of type 'System.Object' and try again.
Invoke-SSHCommand: C:\Users\nxf88094\Downloads\scripts\scripts\QualityCheck\QualityCheck.ps1:982

Similar to above error there are multiple issues.

Kindly let me know if you have any correction or something which i am missing. 

Regards,
Suhas
[error.docx](https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/files/9382567/error.docx)

**Comment by msftphleiten** [comment]
thanks Suhas, this issue will be fixed in next version

**Comment by suhasprabhu680** [comment]
Thanks for the quick reply Phillip. Just to add the script helps a lot and can be used as a part of QA acceptance.

**Comment by msftphleiten** [comment]
fixed in latest version
