### ISSUE TITLE
Latency report is showing only one way result

### ISSUE THREAD

**Issue by alokranjan-fr** [Azure/SAP-on-Azure-Scripts-and-Utilities#91]
Latency report is showing only one way result

![image](https://user-images.githubusercontent.com/113363416/189674330-84c2197a-7231-4d80-aca2-4318c28c63d7.png)

**Comment by msftphleiten** [comment]
can you please check if
- all 3 VMs were deployed
- VMs are up and running
you can also try to keep the VMs to further investigate
