### ISSUE TITLE
SSH unable to logon in multirun for Qualitycheck

### ISSUE THREAD

**Issue by bidibulle38** [Azure/SAP-on-Azure-Scripts-and-Utilities#92]
Login fails in multirun

INFO     - Module Az.Network installed
INFO     - Module Az.NetAppFiles installed
INFO     - Script Version 2022082301                                                                                    
ERROR    - SSH - Please check your credentials, unable to logon

The sh session never gets created since the code doesnt run the command, the guilogonmethod is only used in combination with gui.
I worked around it by setting the logonwithuserpassword below.

switch($_qcrun.LogonMethod) {
"UserPassword" {
$script:GUILogonMethod = "UserPassword"
$script:LogonWithUserPassword = $true

**Comment by msftphleiten** [comment]
can you please share the command that you are running?
could you share the multirun file?
you can send it to phleiten@microsoft.com
