### ISSUE TITLE
Feature Request - Quality Check - Check limits on sidadm and sapadm

### ISSUE THREAD

**Issue by biznacho2000** [Azure/SAP-on-Azure-Scripts-and-Utilities#95]
Ran into a situation where a HANA cluster was failed over because open file limit on sapadm was set too low causing one of the SAP control services to hang.

**Comment by msftphleiten** [comment]
Hi,
what would be the setting to check?
is there a corresponding SAP note?
Thanks

**Comment by msftphleiten** [comment]
closing due to no answer
