### ISSUE TITLE
Small issue with "AdditionalInfo" in ASCS-HA-SLE-0011

### ISSUE THREAD

**Issue by Darryl-G** [Azure/SAP-on-Azure-Scripts-and-Utilities#98]
In Check ASCS-HA-SLE-0011 the AdditionalInfo says that it is checking for "60", but it actually checks for "120".

 "AdditionalInfo": "Checking for msgwait timeout 60",

**Comment by msftphleiten** [comment]
thanks @Darryl-G I will update the info in the next version

**Comment by msftphleiten** [comment]
fixed in latest release
