### ISSUE TITLE
QualityCheck : ANF ThroughputMibps can not get

### ISSUE THREAD

**Issue by jfujimo** [Azure/SAP-on-Azure-Scripts-and-Utilities#99]
ANF volume throughput appear "0" because Get-aznetappfilesvolume command can not get  ThroughputMibps parameter. If we execute command Get-aznetappfilesvolume , ThroughputMibps parameter become blank.
We have to install previous version of Powershell module Az.Netapp.

**Comment by msftphleiten** [comment]
Can you please share the output of the Get-AzNetAppFilesVolume and the versions used for PowerShell and the Module?

**Comment by jfujimo** [comment]
Powershell module  Az.NetappFiles
   version  :  0.13.1  ⇒ NG
                    0.8.0　⇒ OK
![cmdlet_output](https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/assets/147046766/4db0a4a6-bdc0-42f6-94ff-4534a9ef4104)
upper : ver. 0.8.0
lower : ver. 0.13.1

I tried  install old version of Az.NeappFiles module(ver.0.8.0) by overwrite. I can get ThroughputMibps parameter.
We maybe should install module with old version using requiredversion parameter for "Install-Module Az.NetAppFiles -Force" or wait for fixing the output of  the  Get-AzNetAppFilesVolume.

**Comment by msftphleiten** [comment]
Is the ANF in the same subscription/resource-group as the SAP system or are they running in different subscriptions/resource-group?

**Comment by jfujimo** [comment]
It had deployed in the sample subscription/resource-group.

**Comment by msftphleiten** [comment]
can you please share the HTML output with me directly on phleiten@microsoft.com

**Comment by jfujimo** [comment]
Yes. I will send you later.

**Comment by msftphleiten** [comment]
fixed in version 2023112102
